### ISSUE TITLE
Censor API keys in stdout logs

### ISSUE THREAD

**Issue by jwflory** [gridhead/pagure-exporter#58]
The API keys are printed into plain text in `stdout` output. This is dangerous for cases where logs are public or when working in a shared environment. It is also easy to copy+paste them by accident without realizing they are there. Therefore, the `stdout` output should use some neutral placeholder for the API key when printing out.

**Comment by gridhead** [comment]
Hi @jwflory, fair point.

I have made #62, merging which should solve this issue.

Here's what it looks like.

![image](https://github.com/gridhead/pagure-exporter/assets/49605954/ec1c47cc-71d4-4d63-8873-a20c0192567f)

**Comment by jwflory** [comment]
That is perfect!
